version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data/

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - /app:/app/project/media/
    env_file:
      - .env
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: celery --workdir project -A config worker -l INFO --pool solo
    volumes:
      - /app:/app/project/media/
    container_name: celery
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - django
