# fly.toml file generated for pyweb7-goit-team1 on 2023-02-14T12:07:08+02:00

app = "pyweb7-goit-team1"
processes = []

[env]
  DB_HOST = "pyweb7-goit-team1-db.internal"
  DB_NAME = "postgres"
  DB_PASSWORD = "wxWEgIlL0sJWUQh"
  DB_PORT = "5433"
  DB_USER = "postgres"
  DROPBOX_APP_KEY = "f2f9n89cnfrsd92"
  DROPBOX_APP_SECRET = "ocfqxjt4drg0rda"
  DROPBOX_OAUTH2_REFRESH_TOKEN = "R7n6o5G8dHgAAAAAAAAAAayq5ls6uMKzGuVJxYO6vLRRG6DTpam_0t3nAIVoWPo3"
  DROPBOX_ROOT_PATH = "/uploads"
  SECRET_KEY = "django-insecure-1lmyor= $cql0*e50_kbg6+z1k$du2g^-@fqdgf3%2e#p-7yvc="

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
