# Generated by Django 4.1.6 on 2023-02-12 06:36

import autoslug.fields
from django.db import migrations, models
import utils.file_categories


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to=utils.file_categories._get_folder_name,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(
                default=None, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                default=None, max_length=15, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                default=None, max_length=15, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[("f", "female"), ("m", "male"), ("u", "undefined")],
                default="u",
                max_length=1,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=20, populate_from="username", unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="profile",
            table="user_profiles",
        ),
    ]
