# Generated by Django 4.1.6 on 2023-02-13 12:57

from django.db import migrations, models
import utils.file_categories


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_avatar_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='http://pic.onlinewebfonts.com/svg/img_264157.png', upload_to=utils.file_categories._get_folder_name),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
