# Generated by Django 4.1.6 on 2023-02-12 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
    ]
