# Generated by Django 4.1.6 on 2023-02-03 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("birthday", models.DateTimeField()),
                (
                    "phones",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20, unique=True),
                        size=None,
                    ),
                ),
            ],
        ),
    ]
