# Generated by Django 4.1.6 on 2023-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
