# Generated by Django 4.1.6 on 2023-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="contact",
            name="birthday",
            field=models.DateField(),
        ),
    ]
