# Generated by Django 4.1.6 on 2023-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_address_alter_contact_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_addr",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="email",
            name="type",
            field=models.CharField(
                blank=True, choices=[("w", "work"), ("p", "personal")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="phone",
            name="type",
            field=models.CharField(
                blank=True, choices=[("w", "work"), ("p", "personal")], max_length=1
            ),
        ),
    ]
